### ISSUE TITLE
date is correct but time is not!

### ISSUE THREAD

**Issue by nima-mrd** [SharifAIChallenge/aic_site#149]
please fix the time on the website (panel)!
it shows 3 hours and a half less than time zone in Iran.

**Comment by altostratous** [comment]
It is UTC time as the competition is international :p  
It will be addressed soon.

**Comment by nima-mrd** [comment]
@altostratous oh :D !!
ok thanks ;)

**Comment by nima-mrd** [comment]
@altostratous can you set the time based on the chosen language in the panel? I think it's better!

**Comment by altostratous** [comment]
Fixed. See #167.
