### ISSUE TITLE
show played map in competetion list

### ISSUE THREAD

**Issue by ahmadalli** [SharifAIChallenge/aic_site#164]

**Comment by SinaKarimi7** [comment]
and fix invert color in map (beside fix report winner color)

**Comment by ahmadalli** [comment]
@SinaKarimi7 I think this should be discussed at https://github.com/SharifAIChallenge/AIC18_Graphics

**Comment by faryabimm** [comment]
And show score for each team

**Comment by faryabimm** [comment]
Added requested features ;)
