### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by SEMSOFT** [SharifAIChallenge/aic_site#170]
سلام
من کدم رو که توی سایت سابمیت میکنم این کامپایل ارور رو میخوره : 

> ...Wsign-compare] for (size_t j = 0; j < other.get_height(); ++j) ^ [ 80%] Building CXX object client/CMakeFiles/client.dir/src/Model/World.cpp.o [ 84%] Building CXX object client/CMakeFiles/client.dir/src/Model/Entity.cpp.o [ 88%] Building CXX object client/CMakeFiles/client.dir/src/Model/Point.cpp.o [ 92%] Building CXX object client/CMakeFiles/client.dir/src/AI/AI.cpp.o c++: internal compiler error: Killed (program cc1plus) Please submit a full bug report, with preprocessed source if appropriate. See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions. client/CMakeFiles/client.dir/build.make:518: recipe for target 'client/CMakeFiles/client.dir/src/AI/AI.cpp.o' failed make[2]: *** [client/CMakeFiles/client.dir/src/AI/AI.cpp.o] Error 4 CMakeFiles/Makefile2:85: recipe for target 'client/CMakeFiles/client.dir/all' failed make[1]: *** [client/CMakeFiles/client.dir/all] Error 2 Makefile:127: recipe for target 'all' failed make: *** [all] Error 2 

ممنون میشم راهنمایی کنید.
کد توی سیستم خودم کامپایل میشه و ایرادی نداره

**Comment by ali-bahjati** [comment]
We have made some changes to our compiling system, please try again and report if the issue exists.
