### ISSUE TITLE
Shows user green but says not yet accepted

### ISSUE THREAD

**Issue by RasoulAM** [SharifAIChallenge/aic_site#178]

**Comment by faryabimm** [comment]
@RasoulAM could you provide more information on this issue or a screenshot,
or instructions on how to reproduce it?

**Comment by RasoulAM** [comment]
Hello Mr. Faryabi
Mr. Ali Asgari wrote thus issue with my labtop. Ask him:)

Best regards

**Comment by faryabimm** [comment]
fixed in 22c13a7
